version: 2

models:
  - name: stg_jaffle_shop__customers
    description: Staged customer data from our jaffle shop app.
    columns:
      - name: customer_id
        description: Unique identifier for each customer.
        tests:
          - unique
          - not_null
  - name: stg_jaffle_shop__orders
    columns:
      - name: order_id
        description: Unique identifier for each order.
        tests:
          - unique
          - not_null
      - name: status
        description: "{{ doc('status_description') }}"
        tests:
          - accepted_values:
              values: ['shipped', 'completed', 'return_pending', 'returned', 'placed']
      
      - name: customer_id
        description: Foreign key to stg_customers.customer_id.
        tests:
          - relationships:
              to: ref('stg_jaffle_shop__customers')
              field: customer_id